In [1]:
import numpy as np

In [44]:
class Environment:
    def __init__(self):
        self.v = np.zeros((4, 4))

    def update(self):
        # 새로운 v와 기존의 v가 거의 같아질 때까지 반복
        cnt = 0
        while True:
            
            new_v = np.zeros((4, 4))
            for row in range(4):
                for col in range(4):
                    if row == 0 and col == 0 or row == 3 and col == 3:
                        continue
                    
                    new_v[row, col] = self.get_new_v(row, col)    
            cnt +=1
            if np.sum(np.abs(self.v - new_v)) < 1e-4:
                print(cnt)
                break

            self.v = new_v

    def get_new_v(self, row, col):
        # update 함수를 위한 각 상태에 대한 다음 가치 함수의 값을 가져옴
        k = 0
        action_set = {0: [-1, 0], 1: [1, 0], 2: [0, -1], 3: [0, 1]}
        for action in range(4):
            new_row = row + action_set[action][0]
            new_col = col + action_set[action][1]
            if new_row < 0 or new_col < 0 or new_row > 3 or new_col > 3:
                continue
            k += -1 + self.v[new_row, new_col]
            
        return k/4

    def get_policy(self):
        action_table = {0: [-1, 0], 1: [1, 0], 2: [0, -1], 3: [0, 1]}
        dir_table = {0: "↑", 1: "↓", 2: "←", 3: "→"}
        direction_list = []
        for row in range(4):
            direction_list_row = []
            for col in range(4):
                if row == 0 and col == 0 or row == 3 and col == 3:
                    direction_list_row.append("* ")
                    continue
                direction = ""
                action_value = []
                for action in range(4):
                    row_tar = row + action_table[action][0]
                    col_tar = col + action_table[action][1]

                    if row_tar < 0 or row_tar > 3 or col_tar < 0 or col_tar > 3:
                        action_value.append(-999)
                    else:
                        action_value.append(self.v[row_tar, col_tar])

                max_idx_list = np.argwhere(np.isclose(action_value, np.max(action_value))).flatten().tolist()

                for i in max_idx_list:
                    direction += dir_table[i]
                direction += " " * (2-len(max_idx_list))
                direction_list_row.append(direction)
            direction_list.append(direction_list_row)
        return np.array(direction_list)


env = Environment()
print("초기 가치 함수")
print(env.v)

env.update()
print("\n무작위 정책으로 수렴할 때까지 반복한 가치 함수")
print(env.v)

print("\n가치 함수로부터 행동을 결정하는 정책")
print(env.get_policy())

초기 가치 함수
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
48

무작위 정책으로 수렴할 때까지 반복한 가치 함수
[[ 0.         -2.80432336 -3.26083989 -2.13041589]
 [-2.80432336 -4.95647453 -5.10864671 -3.26083989]
 [-3.26083989 -5.10864671 -4.95647453 -2.80432336]
 [-2.13041589 -3.26083989 -2.80432336  0.        ]]

가치 함수로부터 행동을 결정하는 정책
[['* ' '← ' '→ ' '↓←']
 ['↑ ' '↑←' '↑→' '↑ ']
 ['↓ ' '↓←' '↓→' '↓ ']
 ['↑→' '← ' '→ ' '* ']]
